In [ ]:
import numpy as np

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
i = np.arange(10, 20)
print(i)
rang_arr = np.arange(0, 10, 2)
print(rang_arr)

[10 11 12 13 14 15 16 17 18 19]
[0 2 4 6 8]


In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
np.eye(3, dtype = np.int64)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones(4, dtype = np.int64)

array([1, 1, 1, 1])

In [ ]:
np.empty((2, 2))

array([[4.99709196e-310, 0.00000000e+000],
       [4.99618280e-310, 4.99618280e-310]])

In [ ]:
np.reshape(arr, (4, 3) )

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.reshape(arr, (4, 3), order = 'F' )

array([[ 1,  6, 11],
       [ 5, 10,  4],
       [ 9,  3,  8],
       [ 2,  7, 12]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.mean(arr)

6.5

In [ ]:
np.sum(arr)

78

In [ ]:
np.min(arr)

1

In [ ]:
np.max(arr)

12

In [ ]:
np.argmin(arr)    #returns the index of the minimum number

0

In [ ]:
np.argmax(arr)

11

In [ ]:
np.random.rand(3, 2)

array([[0.397549  , 0.96226616],
       [0.38839752, 0.36587935],
       [0.25705783, 0.8041777 ]])

In [ ]:
np.random.randn(3, 2)

array([[-0.85625285, -2.46736195],
       [ 0.34334051,  1.15526601],
       [-0.61243853, -0.357054  ]])

In [ ]:
np.random.randint(-5, 4, size = (4, 3))   #Return random integers from low (inclusive) to high (exclusive).

array([[ 2,  2,  3],
       [-4,  2,  3],
       [-4, -4,  1],
       [-5, -5,  0]])

In [ ]:
np.dot(a, b)   #matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a[1:2]

array([[3, 4]])

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])

result = x + y  # Broadcasting the 'b' array to match the shape of 'a'
print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

sqrt_arr = np.sqrt(arr)
exp_arr = np.exp(arr)
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)
log_arr = np.log(arr)
print(sqrt_arr)
print(exp_arr)
print(sin_arr)
print(cos_arr)
print(log_arr)

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
a = np.arange(6)
a.shape
# a2 = a[np.newaxis, :]
# a2.shape

(6,)